# ISSUES:
#
# need to install esbuild:
# npm install -g esbuild
#
# prisma is problematic
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ino-estc-services

  Sample SAM Template for ino-estc-services
  
Globals:
  Function:
    Timeout: 30
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  TournamentService:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: .aws-sam/build/TournamentService
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          DATABASE_URL: "mongodb+srv://estc:dRUM44GLsbVMdKDP@estc.fjtut.mongodb.net/tournament-service?retryWrites=true&w=majority"
      Events:
        CreateTournament:
          Type: Api 
          Properties:
            Path: /createTournament
            Method: post
      MemorySize: 256
      VpcConfig: 
        SecurityGroupIds:
          - sg-095e1adef797b94ea
        SubnetIds:
          - subnet-0b180ff511fc72a42
          - subnet-09d23a73422f404b8
          - subnet-0cc9ba56866e576f1
          - subnet-06a34a022126ac6b3
          - subnet-03f0e233f8788e9b6
          - subnet-07573745f0487de3f

Outputs:
  TournamentServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/createTournament/"
  TournamentService:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TournamentService.Arn
  TournamentServiceIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TournamentServiceRole.Arn
